apiVersion: apps/v1
kind: Deployment
metadata:
  name: Data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Data
  template:
    metadata:
      labels:
        app: Data
  spec:
    containers:
        - name: Data
          image: prxo/my-project:02
          
